######################################################################
# Automatically generated by qmake (3.1) Mon Sep 19 22:58:01 2022
######################################################################

message($$CONFIG)

CONFIG += c++latest strict_c++

debug {
QMAKE_CXXFLAGS_DEBUG -= -std=gnu++1z
QMAKE_CXXFLAGS_DEBUG += -std=c++26 -Wall -Wextra -g -O1 -march=x86-64
QMAKE_LFLAGS_DEBUG += -Wl,-O1
TARGET = signalbackup-viewer_debug
message(debug build)
}
release {
QMAKE_CXXFLAGS_RELEASE -= -O2 -g -march=i686 -mtune=atom -mtune=generic -std=gnu++1z
QMAKE_CXXFLAGS_RELEASE += -std=c++26 -Wall -Wextra -O3 -march=native -flto
QMAKE_CFLAGS_RELEASE -= -O2 -g -march=i686 -mtune=atom -mtune=generic -std=gnu++1z
QMAKE_CFLAGS_RELEASE += -std=c++26 -Wall -Wextra -O3 -march=native -flto
QMAKE_LFLAGS_RELEASE -= -Wl,-O1
QMAKE_LFLAGS_RELEASE += -s -O3 -flto=auto
TARGET = signalbackup-viewer
message(release build)
}

TEMPLATE = app
INCLUDEPATH += .
RESOURCES = signalbackup-viewer.qrc

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

DEFINES *= QT_USE_QSTRINGBUILDER

LIBS += -lcrypto -lvlc
QT += widgets sql
CONFIG += qt thread object_parallel_to_source c++26
OBJECTS_DIR=GENERATEDOBJECTS

# Input
HEADERS += common_fe.h \
           shared/common_be.h \
           shared/common_bytes.h \
           shared/common_filesystem.h \
           shared/androidattachmentreader/androidattachmentreader.h \
           shared/attachmentframe/attachmentframe.h \
           shared/attachmentmetadata/attachmentmetadata.h \
           shared/avatarframe/avatarframe.h \
           shared/backupframe/backupframe.h \
           shared/base64/base64.h \
           shared/baseattachmentreader/baseattachmentreader.h \
           shared/cryptbase/cryptbase.h \
           shared/databaseversionframe/databaseversionframe.h \
           shared/endframe/endframe.h \
           shared/filedecryptor/filedecryptor.h \
           shared/framewithattachment/framewithattachment.h \
           shared/groupv2message/groupv2message.h \
           shared/headerframe/headerframe.h \
           shared/invalidframe/invalidframe.h \
           shared/keyvalueframe/keyvalueframe.h \
           shared/logger/logger.h \
           shared/msgrange.h \
           shared/msgtypes/msgtypes.h \
           shared/protobufparser/protobufparser.h \
           shared/sharedprefframe/sharedprefframe.h \
           shared/sqlstatementframe/sqlstatementframe.h \
           shared/stickerframe/stickerframe.h \
           conversationlistview/conversationlistview.h \
           conversationlistviewdelegate/conversationlistviewdelegate.h \
           conversationloadingdelegate/conversationloadingdelegate.h \
           conversationmodelitem/conversationmodelitem.h \
           conversationsqlmodel/conversationsqlmodel.h \
           emojitextdocument/emojitextdocument.h \
           mediaplayer/mediaplayer.h \
           mediapreviewgenerator/mediapreviewgenerator.h \
           messagedetailswidget/messagedetailswidget.h \
           msgattachment/msgattachment.h \
           mutexprotecteditem/mutexprotecteditem.h \
           recipientpreferences/recipientpreferences.h \
           sbvmainwindow/sbvmainwindow.h \
           searchhighlighter/searchhighlighter.h \
           searchwidget/searchwidget.h \
           signallistviewbase/signallistviewbase.h \
           signalviewdelegatebase/signalviewdelegatebase.h \
           threadlistview/threadlistview.h \
           threadsqlmodel/threadsqlmodel.h \
           threadviewdelegate/threadviewdelegate.h \
           vlcbase/vlcbase.h \
           columnnames/columnnames.h
SOURCES += main.cc \
           shared/attachmentframe/statics.cc \
           shared/attachmentmetadata/getattachmentmetadata.cc \
           shared/avatarframe/statics.cc \
           shared/backupframe/init.cc \
           shared/cryptbase/getbackupkey.cc \
           shared/cryptbase/getcipherandmac.cc \
           shared/databaseversionframe/statics.cc \
           shared/endframe/statics.cc \
           shared/filedecryptor/filedecryptor.cc \
           shared/filedecryptor/getframe.cc \
           shared/filedecryptor/getframebrute.cc \
           shared/filedecryptor/initbackupframe.cc \
           shared/framewithattachment/setattachmentdata.cc \
           shared/groupv2message/groupv2message.cc \
           shared/headerframe/statics.cc \
           shared/keyvalueframe/statics.cc \
           shared/logger/isterminal.cc \
           shared/logger/outputhead.cc \
           shared/logger/statics.cc \
           shared/logger/supportsansi.cc \
           shared/sharedprefframe/statics.cc \
           shared/sqlstatementframe/buildstatement.cc \
           shared/sqlstatementframe/statics.cc \
           shared/stickerframe/statics.cc \
           conversationlistview/conversationlistview.cc \
           conversationlistviewdelegate/conversationlistviewdelegate.cc \
           conversationlistviewdelegate/paint.cc \
           conversationlistviewdelegate/sizehint.cc \
           conversationloadingdelegate/conversationloadingdelegate.cc \
           conversationmodelitem/conversationmodelitem.cc \
           conversationsqlmodel/conversationsqlmodel.cc \
           conversationsqlmodel/workerthread.cc \
           emojitextdocument/getemojipos.cc \
           emojitextdocument/statics_emoji.cc \
           emojitextdocument/applyranges.cc \
           mediaplayer/mediaplayer.cc \
           mediapreviewgenerator/getrgb.cc \
           mediapreviewgenerator/mediapreviewgenerator.cc \
           mediapreviewgenerator/rotate90.cc \
           messagedetailswidget/messagedetailswidget.cc \
           msgattachment/msgattachment.cc \
           mutexprotecteditem/mutexprotecteditem.cc \
           recipientpreferences/recipientpreferences.cc \
           sbvmainwindow/sbvmainwindow.cc \
           searchhighlighter/searchhighlighter.cc \
           searchwidget/searchwidget.cc \
           signallistviewbase/signallistviewbase.cc \
           signalviewdelegatebase/signalviewdelegatebase.cc \
           threadsqlmodel/threadsqlmodel.cc \
           threadviewdelegate/threadviewdelegate.cc \
           vlcbase/destructor.cc \
           vlcbase/durationchanged.cc \
           vlcbase/preparsed.cc \
           vlcbase/vlcbase.cc \
           columnnames/columnnames.cc \
           columnnames/statics.cc
